version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        standard:
            format: '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(levelname)s]- %(message)s'
            datefmt: '%a, %d %b %Y %H:%M:%S'
handlers:
    console:
            class: logging.StreamHandler
            level: INFO
            formatter: simple
            stream: ext://sys.stderr
    console_err:
            class: logging.StreamHandler
            level: ERROR
            formatter: simple
            stream: ext://sys.stderr
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: 'D:/pycode/appo/result/log/info.log'
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: 'D:/pycode/appo/result/log/errors.log'
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:
    debugLog:
            level: DEBUG
            handlers:  [console]
            propagate: 1
    infoLog:
            level: INFO
            handlers:  [console]
            propagate: 1
#    warningLog:
#            level: WARNING
#            handlers: [warning_file_handler]
#            propagate: 1
    errorLog:
            level: ERROR
            handlers: [console]
            propagate: 0
#    criticalLog:
#            level: CRITICAL
#            handlers: [critical_file_handler]
#            propagate: 1
root:
    level: INFO
    handlers: [info_file_handler,error_file_handler,console]
    propagate: 1